services:
  app:
    image: laxyy/chitychat
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_HOST=db
    env_file:
      - .env
    volumes: 
      - ./server/server.crt:/app/server/server.crt:ro
      - ./server/server.key:/app/server/server.key:ro
      - ./client/public/upload:/app/client/public/upload:rw
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=chitychat
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
