services:
  cc_server:
    image: chitychat/cc_server
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - NATS_URL=nats
      - CC_REDIS_IP=redis
    env_file:
      - .env
    volumes: 
      - ./backend/server/server.crt:/app/backend/server/server.crt:ro
      - ./backend/server/server.key:/app/backend/server/server.key:ro
    depends_on:
      - db
      - nats
      - redis

  # cc_hubs:
  #   image: chitychat/cc_hubs 
  #   environment:
  #     - NATS_URL=nats
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - nats
  #   restart: unless-stopped
  #
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=chitychat
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    restart: unless-stopped

volumes:
  pg_data:
