name: CI/CD Docker Pipeline

on:
  push:
    branches: [ "main", "dev" ] 
    paths:
      - 'server/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - '.github/workflows/**'
      - 'meson.build'
      - '.dockerignore'
      - 'client/public/**'
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Installing packages
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose python3-websockets
      
      - name: Create `.env` file for database credentials
        run: |
          echo "DB_USER=test_user" > .env
          echo "DB_PASSWORD=test_pass" >> .env
      
      - name: Create SSL certs
        run: openssl req -x509 -newkey rsa:4096 -keyout server/server.key -out server/server.crt -days 365 -nodes -subj "/CN=localhost"

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/chitychat .
      
      - name: Start containers using docker-compose
        run: docker-compose up -d
      
      - name: Run Chat Server tests
        run: python3 tests/run_all_tests.py || { docker-compose logs app && exit -1; }
      
      - name: Stop and remove containers
        run: docker-compose down --volumes

      - name: Save Docker Image
        if: github.ref == 'refs/heads/main'
        run: docker save ${{ vars.DOCKERHUB_USERNAME }}/chitychat | gzip > chitychat-image.tar.gz
      
      - name: Upload Docker image as artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: chitychat-image
          path: chitychat-image.tar.gz
          retention-days: 1
  
  deploy:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: DockerHub

    steps:
      - name: Download Docker Image artifact
        uses: actions/download-artifact@v4
        with:
          name: chitychat-image
      
      - name: Load Docker Image
        run: gunzip -c chitychat-image.tar.gz | docker load

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/chitychat