name: CI/CD with Docker Compose.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create `.env` file for database credentials
        run: |
          echo "DB_USER=test_user" > .env
          echo "DB_PASSWORD=test_pass" >> .env
      
      - name: Start containers using docker-compose
        run: |
          docker-compose up -d
          sleep 30
      
      - name: Stop and remove containers
        run: docker-compose down --volumes
  
  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build and tag Docker image
        run: docker-compose Build